### ISSUE TITLE
Not working on latest versions from Unraid

### ISSUE THREAD

**Issue by ich777** [ssttevee/zig-hailo#1]
Hi @ssttevee 

I noticed that hailostatus isn't working anymore on the latest versions from Unraid and it gives this back:
```
errno? 25 NOTTY
error: Unexpected
```

Is it maybe related to this PR:
https://github.com/unraid/webgui/pull/1835

**Comment by ssttevee** [comment]
I'm not sure when I'll be able to investigate this. I'm still on version 6.12.10 and cannot seem to update.

Is this related to unraid 6 or 7?

Does this occur both in the terminal and the webgui?

Does the the official `hailortcli` command work?

**Comment by ich777** [comment]
I'm not 100% sure since it could be also an issue with the driver.
A user reported on the Unraid Forums reported that it's not working anymore [here](https://forums.unraid.net/topic/92865-support-ich777-amd-vendor-reset-coraltpu-hpsahba/?do=findComment&comment=1473433).

I'm on the new beta but the user who initially reported it is on 6.12.13

I actually believe it's related to the driver version that you are using, version 4.18.0 does spit out that error, 4.17.1 not:
```
Device: /dev/hailo0 (0000:05:00.00)
Driver Version: 4.17.1
Max Page Size: 4096
Board Type: hailo8
Allocation Mode: userspace
DMA Type: pcie
DMA Engines Count: 1
Is Firmware Loaded: false
Control Protocol Version: 2
Firmware Version: 4.17.1 (release, app, extended context switch buffer)
Logger Version: 0
Board Name: Hailo-8
Device Architecture: HAILO8L
Serial Number: HLDDLBB242500722
Part Number: HM21LB1C2LAE
Product Name: HAILO-8L AI ACC M.2 B+M KEY MODULE EXT TMP
Core Clock Rate: 400000000Hz
Supported Features: ethernet           false
                    mipi               false
                    pcie               true
                    current_monitoring false
                    mdio               false
Boot Source: pcie
LCS: 3
SOC ID: 73F1CA6B60DBC51FF42CF55DE43521E067C9F33C18077DB4DE7E545926684BC8
Ethernet MAC Address: 00:00:00:00:00:00
ULT ID: 0060C1BB8AB218506923FAFB
PM Values: 02400100000297010000021A020000FB8A3E4261233E4201
Partial Clusters Layout Bitmap: unknown
Measured Power: unavailable
Temperature: S0  47.736897C
             S1  47.585136C
             Avg 47.66102C
```

For now I removed the code from the plugin which uses `hailostatus` since this has also prevented the Dashboard to load.

**Comment by ich777** [comment]
I'm not 100% sure since it could be also an issue with the driver.
A user reported on the Unraid Forums reported that it's not working anymore [here](https://forums.unraid.net/topic/92865-support-ich777-amd-vendor-reset-coraltpu-hpsahba/?do=findComment&comment=1473433). I think his system log is spammed because the plugin page tries to access `hailostatus` every 5 seconds to get the new status.

I'm on the new beta but the user who initially reported it is on 6.12.13

I actually believe it's related to the driver version that you are using, version 4.18.0 does spit out that error, 4.17.1 not:
```
Device: /dev/hailo0 (0000:05:00.00)
Driver Version: 4.17.1
Max Page Size: 4096
Board Type: hailo8
Allocation Mode: userspace
DMA Type: pcie
DMA Engines Count: 1
Is Firmware Loaded: false
Control Protocol Version: 2
Firmware Version: 4.17.1 (release, app, extended context switch buffer)
Logger Version: 0
Board Name: Hailo-8
Device Architecture: HAILO8L
Serial Number: HLDDLBB242500722
Part Number: HM21LB1C2LAE
Product Name: HAILO-8L AI ACC M.2 B+M KEY MODULE EXT TMP
Core Clock Rate: 400000000Hz
Supported Features: ethernet           false
                    mipi               false
                    pcie               true
                    current_monitoring false
                    mdio               false
Boot Source: pcie
LCS: 3
SOC ID: REMOVED
Ethernet MAC Address: 00:00:00:00:00:00
ULT ID: REMOVED
PM Values: REMOVED
Partial Clusters Layout Bitmap: unknown
Measured Power: unavailable
Temperature: S0  47.736897C
             S1  47.585136C
             Avg 47.66102C
```

For now I removed the code from the plugin which uses `hailostatus` since this has also prevented the Dashboard to load.

EDIT: With any driver newer than 4.17.1 I get this message in the syslog after calling `hailostatus`:
```
Oct 11 13:35:02 TestServer2 kernel: hailo 0000:05:00.0: Invalid general ioctl code 0x400c6705 (nr: 5)
```
(this is with Hailo RT Driver version 4.19.0, however it seems the Hailo driver has loaded properly and is also working properly from what I can see in the syslog)

**Comment by ssttevee** [comment]
I have pushed an update that adds 4.18 driver compatibility as well as a graceful fail path for incompatible driver protocol changes. Please reopen if it's still an issue.

I did also see that [v4.19 driver](https://github.com/hailo-ai/hailort/tree/3d673252095c11a99147a6e72b4c11150ebd0882) was published, but I've decided to tackle that another day (partially because it's not built for unraid yet).

**Comment by ich777** [comment]
@ssttevee thanks for the fix, I will update the plugin ASAP.

However the driver is already compiled for newer version from Unraid.
I might have to update my routine to include the Hailo driver to be also auto compiled if a newer version is released for the latest available stable version from Unraid.
